version: 0.2



phases:
   build:
     commands:
        - echo Entered the build phase...
        - mvn clean package
   post_build:
      commands:
        - echo Build completed successfully
artifacts:
   files:
     - target/cde-027-code-pipeline-git.jar
   discard-paths: yes